In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

GAGAL , AKURASI KURANG

In [2]:

#preprocessing
#download csv
#!gdown "1XtKRlTEjPN-Yp65cZKuiEcGxzr4HCY8D"

#download csv preprocess
!gdown "1-4zBG5E6QD2RQ7u2Oygj049j4qRPQ3a6"
!gdown "1q2qL3QnAV1KsrgyGNuDopY3cjbAofMPy"
!gdown "1-4vKWxEKfIW_Hjo93T5U2X26ZV-L3KSA"
!gdown "1cos1toN-hpQavSRtdwmsroUau6xUreyU"
!gdown "1I6Ey2CyKzyUDG5qHzcb8hqvPjDm9Sb7_"

Downloading...
From: https://drive.google.com/uc?id=1-4zBG5E6QD2RQ7u2Oygj049j4qRPQ3a6
To: /content/MH_Campaign_sentiment.csv
100% 143M/143M [00:01<00:00, 123MB/s]
Downloading...
From: https://drive.google.com/uc?id=1q2qL3QnAV1KsrgyGNuDopY3cjbAofMPy
To: /content/poem_sentiment.csv
100% 40.6k/40.6k [00:00<00:00, 71.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=1-4vKWxEKfIW_Hjo93T5U2X26ZV-L3KSA
To: /content/sentimen140.csv
100% 124M/124M [00:01<00:00, 74.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1cos1toN-hpQavSRtdwmsroUau6xUreyU
To: /content/tweet_sentiment_extraction.csv
100% 2.24M/2.24M [00:00<00:00, 93.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1I6Ey2CyKzyUDG5qHzcb8hqvPjDm9Sb7_
To: /content/tambahan_netral.csv
100% 273k/273k [00:00<00:00, 101MB/s]


In [3]:


# Inisialisasi train_set dan val_set
train_kalimat = []
train_score = []
val_kalimat = []
val_score = []


In [4]:
# #PRE PROCESSING
import csv
from tqdm import tqdm
import ast
import re
import numpy as np

# Path data CSV
path1 = "/content/MH_Campaign_sentiment.csv"
path2 = "/content/poem_sentiment.csv"
path3 = "/content/sentimen140.csv"
path4 = "/content/tweet_sentiment_extraction.csv"
path5 = "/content/tambahan_netral.csv"

# Urut dari jumlah data yang paling sedikit
f = [path2, path5, path4, path1, path3]

# Persentase untuk train_set
persen_train_set = 0.98

kalimat_ = []
score_ = []

# Inisialisasi train_set dan val_set
train_kalimat = []
train_score = []
val_kalimat = []
val_score = []

# Membaca data dari berbagai file CSV dan langsung membaginya ke dalam train_set dan val_set
for u in f:
    with open(u, 'r') as file_csv:
        csv_reader = csv.reader(file_csv)
        for baris in tqdm(csv_reader):
            kalimat_baru = re.sub(r'[-.,:;!?\n@#]|//t', ' ', baris[0])  # Preprocessing kalimat
            # String ke list
            skor_baru = np.array(ast.literal_eval(baris[1]))
            kalimat_.append(kalimat_baru)
            score_.append(skor_baru)

# Memutuskan apakah data akan dimasukkan ke dalam train_set atau val_set menggunakan slicing
train_kalimat = kalimat_[:int(len(kalimat_) * persen_train_set)]
train_score = score_[:int(len(kalimat_) * persen_train_set)]
val_kalimat = kalimat_[int(len(kalimat_) * persen_train_set):]
val_score = score_[int(len(kalimat_) * persen_train_set):]

# Menampilkan data training
print("\nData training:", len(train_kalimat))
for i in range(min(3, len(train_kalimat))):
    print(train_kalimat[i])
print("\n{'neg':, 'neu':, 'pos':,}")
print(train_score[:3])

# Menampilkan data val
print("\nData val:", len(val_kalimat))
for i in range(min(3, len(val_kalimat))):
    print(val_kalimat[i])
print("\n{'neg':, 'neu':, 'pos':,}")
print(val_score[:3])


771it [00:00, 34557.36it/s]
5458it [00:00, 25880.64it/s]
31015it [00:01, 30926.16it/s]
724745it [00:24, 29884.60it/s]
1599999it [00:34, 46741.30it/s]



Data training: 2314748
it flows so long as falls rain
when i peruse conquered fame heroes victories mighty generals i do not envy generals
inward strife truth liberty

{'neg':, 'neu':, 'pos':,}
[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]

Data val: 47240
shriansh Hi That might be so but it doesn't make it right  Thanks anyway
Never realised switch my bedside light glows dark before
Ef why eye My new twit name vanhaylei

{'neg':, 'neu':, 'pos':,}
[array([0, 0, 1]), array([0, 0, 1]), array([0, 0, 1])]


In [5]:
print(len(train_kalimat),len(train_score))
print(len(val_kalimat),len(val_score))

2314748 2314748
47240 47240


In [6]:
#Tokenization and Padding
#Tokenization
max_words = 30000  # Set maximum number of words to consider
max_length = 200  # Set maximum length of sequences

tokenizer = Tokenizer(num_words=max_words, oov_token='<OOV>')
tokenizer.fit_on_texts(train_kalimat)



In [ ]:
#untuk proses smote, jangan dijalankan jika sudah punya file .zip berisi npy didrive


# Convert text sequences to integer sequences
train_sequences = tokenizer.texts_to_sequences(train_kalimat)
val_sequences = tokenizer.texts_to_sequences(val_kalimat)




#Padding sequences to ensure uniform length



train_padded = pad_sequences(train_sequences, maxlen=max_length, padding='post', truncating='post')
val_padded = pad_sequences(val_sequences, maxlen=max_length, padding='post', truncating='post')


import numpy as np
from imblearn.over_sampling import SMOTE
from sklearn.feature_extraction.text import TfidfVectorizer

# Misalkan train_score adalah array label kelas (0, 1, 2) dari urutan token
#train_score = np.digitize(train_score, bins=[0.6])
#val_score = np.digitize(val_score, bins=[0.6])

# Menerapkan SMOTE pada urutan token
smote1 = SMOTE(random_state=1)
smote2 = SMOTE(random_state=1)
train_padded_resampled, train_score_resampled = smote1.fit_resample(train_padded, train_score)
val_padded_resampled, val_score_resampled = smote2.fit_resample(val_padded, val_score)


#train_padded_resampled, train_score_resampled = np.array(train_padded), np.array(train_score)
#val_padded_resampled, val_score_resampled = np.array(val_padded), np.array(val_score)


# Cek jumlah tiap kelas
netral = 0
positif = 0
negatif = 0

kelas = ["neg", "neu", "pos"]

for h in train_score_resampled:
    tip = np.argmax(h)
    if kelas[tip] == "neg":
        negatif += 1
    if kelas[tip] == "pos":
        positif += 1
    if kelas[tip] == "neu":
        netral +=1

print("Jumlah semuanya : ", len(train_score_resampled))
print("Netral : ", (netral))
print("Positif : ", (positif))
print("Negatif : ", (negatif))


#tes untuk save smote di laptop karena di colab lama
import zipfile
import shutil

np.save("/content/train_padded.npy",train_padded)
np.save("/content/val_padded.npy",val_padded)
np.save("/content/train_score.npy",train_score)
np.save("/content/val_score.npy",val_score)

with zipfile.ZipFile('file.zip', 'w') as zipf:
      # Menambahkan file .npy ke dalam zip
      zipf.write("/content/train_padded.npy")
      zipf.write("/content/val_padded.npy")
      zipf.write("/content/train_score.npy")
      zipf.write("/content/val_score.npy")





Jumlah semuanya :  2238629
Netral :  690690
Positif :  777767
Negatif :  770172


In [7]:
#download npy yang sudah proses smote dan masukan ke variable
import numpy as np

#link zip berisi npy
!gdown "1GTy62vy1P6efetORLHOfu40ieocw49NN"

!unzip "/content/tes_smote.zip"

train_padded_resampled = np.load("/content/train_padded_smote.npy")
train_score_resampled = np.load("/content/train_score_smote.npy")
val_padded_resampled = np.load("/content/val_padded_smote.npy")
val_score_resampled = np.load("/content/val_score_smote.npy")

# Cek jumlah tiap kelas
netral = 0
positif = 0
negatif = 0

kelas = ["neg", "neu", "pos"]

for h in train_score_resampled:
    tip = np.argmax(h)
    if kelas[tip] == "neg":
        negatif += 1
    if kelas[tip] == "pos":
        positif += 1
    if kelas[tip] == "neu":
        netral +=1

print("Jumlah semuanya : ", len(train_score_resampled))
print("Netral : ", (netral))
print("Positif : ", (positif))
print("Negatif : ", (negatif))

Downloading...
From: https://drive.google.com/uc?id=1GTy62vy1P6efetORLHOfu40ieocw49NN
To: /content/tes_smote.zip
100% 84.9M/84.9M [00:01<00:00, 49.1MB/s]
Archive:  /content/tes_smote.zip
  inflating: train_padded_smote.npy  
  inflating: train_score_smote.npy   
  inflating: val_padded_smote.npy    
  inflating: val_score_smote.npy     
Jumlah semuanya :  2407398
Netral :  802466
Positif :  802466
Negatif :  802466


In [ ]:
# print("Netral : ", (netral[0]))
# print("Positif : ", (positif[0]))
# print("Negatif : ", (negatif[0]))
# print(len(train_padded_resampled), len(val_padded_resampled))

In [8]:
# Model architecture
embedding_dim = 16

model = keras.Sequential([
    keras.layers.Embedding(max_words, embedding_dim, input_length=max_length),

    keras.layers.Bidirectional(keras.layers.LSTM(max_length)) ,
    keras.layers.Flatten(),
    keras.layers.Dense(128,activation = "relu"),
    keras.layers.Dense(128,activation = "relu"),
    keras.layers.Dense(128,activation = "relu"),


    keras.layers.Dense(3, activation='softmax')

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])



# Train the model,
num_epochs = 10
model.fit(train_padded_resampled, train_score_resampled, epochs=num_epochs, validation_data=(val_padded_resampled, val_score_resampled), batch_size = 2224)

Epoch 1/10
1083/1083 [==============================] - 537s 487ms/step - loss: 0.3881 - accuracy: 0.8305 - val_loss: 0.3433 - val_accuracy: 0.8532
Epoch 2/10
1083/1083 [==============================] - 518s 478ms/step - loss: 0.3203 - accuracy: 0.8630 - val_loss: 0.3266 - val_accuracy: 0.8611
Epoch 3/10
1083/1083 [==============================] - 521s 481ms/step - loss: 0.3042 - accuracy: 0.8704 - val_loss: 0.3182 - val_accuracy: 0.8647
Epoch 4/10
1083/1083 [==============================] - 521s 481ms/step - loss: 0.2891 - accuracy: 0.8768 - val_loss: 0.3133 - val_accuracy: 0.8677
Epoch 5/10
1083/1083 [==============================] - 519s 479ms/step - loss: 0.2796 - accuracy: 0.8809 - val_loss: 0.3145 - val_accuracy: 0.8678
Epoch 6/10
1083/1083 [==============================] - 518s 479ms/step - loss: 0.2720 - accuracy: 0.8841 - val_loss: 0.3129 - val_accuracy: 0.8682
Epoch 7/10
1083/1083 [==============================] - 518s 478ms/step - loss: 0.2654 - accuracy: 0.8872 - val_

In [11]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# Evaluate the model on the validation set
loss, accuracy = model.evaluate(val_padded_resampled, val_score_resampled, batch_size = 128)
print(f'Validation accuracy: {accuracy * 100:.2f}%')

In [10]:
#test_set


test_set = ["I don't know how to tell them that I have feelings for my best friend. It's tearing me apart inside.",
            "Love is complicated, and I feel lost in this sea of emotions. Does he/she feel the same way?",
            "The pressure at work is overwhelming. I've been putting in extra hours, but it never seems to be enough.",
            "I'm stuck in a job that I hate. I feel like I've lost all passion for what I do.",
            "My friends have been distant lately, and I don't know what I did wrong. I miss the times when we were so close.",
            "My relationship with my parents is strained, and I wish I could make them understand my point of view.",
            "I can't believe I found someone who understands me completely. Every moment with them feels like a fairytale.",
            "Spending the day doing what I love, whether it's reading, painting, or hiking, fills my heart with happiness.",
            "The car is blue.",
            "My mental health is deteriorating day by day. Dealing with depression feels like being trapped in a never-ending cycle of darkness. I don't know how to escape it."
            ]

kelas = ["neg", "neu", "pos"]

#while True :

for h in test_set :
  #h = input("Masukan kalimat (English) : ")
  toke = tokenizer.texts_to_sequences([h])
  pad = pad_sequences(toke, maxlen=max_length, padding='post', truncating='post')

  output = model.predict(pad)
  print(output)


  print("input : ", h , "\n - prediksi => ", kelas[np.argmax(output)])
  print()

1/1 [==============================] - 1s 963ms/step
[[9.072847e-03 9.899663e-01 9.608327e-04]]
input :  I don't know how to tell them that I have feelings for my best friend. It's tearing me apart inside. 
 - prediksi =>  neu

1/1 [==============================] - 0s 33ms/step
[[0.77903    0.21874826 0.00222163]]
input :  Love is complicated, and I feel lost in this sea of emotions. Does he/she feel the same way? 
 - prediksi =>  neg

1/1 [==============================] - 0s 51ms/step
[[0.75697726 0.14849654 0.09452615]]
input :  The pressure at work is overwhelming. I've been putting in extra hours, but it never seems to be enough. 
 - prediksi =>  neg

1/1 [==============================] - 0s 30ms/step
[[0.93809557 0.01994239 0.04196212]]
input :  I'm stuck in a job that I hate. I feel like I've lost all passion for what I do. 
 - prediksi =>  neg

1/1 [==============================] - 0s 30ms/step
[[0.96830374 0.00200453 0.02969166]]
input :  My friends have been distant lately

In [14]:
import pickle

#simpan model

model.save("/content/drive/MyDrive/model/model_smote.h5")

#simpan tokenizer
with open('/content/drive/MyDrive/model/tokenizer_smote.pkl', 'wb') as file:
    pickle.dump(tokenizer, file)